package com.eat_healthy.tiffin.utils

object Constants   {

    var BASEURL="http://healthytiffinbackend1-env.eba-ymu8qgby.us-east-2.elasticbeanstalk.com"
    const val DEFAULT_BASE_URL = "http://healthytiffinbackend1-env.eba-ymu8qgby.us-east-2.elasticbeanstalk.com"
  //  var BASEURL="http://10.0.2.2:9595"
  //  var DEFAULT_BASE_URL = "http://10.0.2.2:9595"
    const val PLAYSTORE_LINK =
    "https://play.google.com/store/apps/details?id=com.eat_healthy.tiffin&pli=1"
   const val VIEW_HEADER = 0
   const val VIEW_SPECIAL_MEAL = 1
   const val VIEW_MEAL = 2
   const val VIEW_EXTRAS = 3
    const val VIEW_EXTRAS_RADIO = 4
    const val VIEW_EXTRAS_CHECKBOX = 5
   const val VIEW_MEAL_CATEGORY_HEADER = 6
   const val BUTTON = 7
    const val VIEW_CURRIES = 8
   const val VIEW_MEAL_SUMMARY = 9
   const val CURRENT_LOCATION_PREFERENCE="currentLocationPreference"
   const val USER_INFO="userInfo"
   const val MONTHLY_USER="monthlyUser"
   const val USER_CITY_LOCALITY="userCityLocality"
   const val AVAILABLE_LOCALITY_LIST="availableLocalityList"
   const val SABJI="sabji"
   const val RICE_ROTI="rice_roti"
   const val DAL="dal"
   const val EXTRAS="extras"
   const val normalMealCategory="normal"
   const val silverMealCategory="silver"
   const val goldMealCategory="gold"
   const val LUNCH_DINNER="Lunch & Dinner"
   const val LUNCH="Lunch"
   const val DINNER="Dinner"
    const val LUNCH_TIMEOUT = "lunch_timeout"
   const val TIME_OUT="time_out"
   const val SCREEN_ENTRY_POINT="screenEntryPoint"
    const val HOME_PAGE_TAB = "homepage_tab"
    const val REFER_EARN_FROM_HOME = "refer_earn_from_home"
    const val MONTHLY_USER_TAB = "monthlyUserTab"
   const val HOME_PAGE = "home_page"
    const val HOME_PAGE_SUCCESS = "home_page_success"
   const val ACCOUNT = "account"
   const val REFERAL_USER_DATA  = "referal_user_data"
   const val REFERAL_CODE_ORDER_COUNT = "referal_code_order_count"
   const val REFERAl_CODE = "referal_code"
   const val REFERAL_REWARD_MAX_LIMIT_PER_USER = "referalRewardMaxLimitPerUser"
    const val REWARD_PERCENTAGE_PER_ORDER = "rewardPercentagePerOrder"
    const val FOOD_REVIEW = "food_review"
    const val ADD_4_HOURS_TO_ORDER_TIME = "add_4_hours_to_order_time"
    const val GENERIC_STRING_ARRAYLIST = "generic_string_arraylist"
    const val GENERIC_HEADER = "generic_header"
    const val USERS_FOOD_REMINDER = "usersFoodReminder"
    const val MENU = "menu"
    const val LUNCH_WORKER_ENQUED = "lunch_worker_enqued"
    const val DINNER_WORKER_ENQUED = "dinner_worker_enqued"
    const val BASE_COURSE_BOTTOMSHEET_OPENED = "base_course_bottom_sheet_opened"
    const val CART_BOTTOMSHEET_OPENED = "cart_bottom_sheet_opened"
    const val MENU_PAGE_OPENED = "menu_page_opened"
    const val MENU_PAGE_SUCCESS = "menu_page_opened"
    const val LUNCH_REMINDER_CLICKED = "lunch_reminder_clicked"
    const val DINNER_REMINDER_CLICKED = "dinner_reminder_clicked"
    const val FEEDBACK_FORM_OPENED = "feed_back_form_opened"
    const val FEEDBACK_FORM_OPENED_SUCCESSFULLY = "feed_back_form_opened_successfully"
    const val FEEDBACK_FORM_SUBMITTED = "feed_back_form_submitted"
    const val FOOD_REVIEW_BOTTOMSHEET_OPENED = "food_review_bottomsheet_opened"
    const val FOOD_REVIEW_BOTTOMSHEET_CANCELED = "food_review_bootsheet_canceled"
    const val FOOD_REVIEW_SUBMITTED = "food_review_submitted"
    const val ORDER_SUCCESSS_PAGE = "order_success_page"
    const val FEEDBACK_BTN_CLICKED_FROM_SUCCESSS_PAGE = "feedback_btn_clicked_from_success_page"
    const val TIMESLOT_BTN_CLICKED_FROM_SUCCESSS_PAGE = "timeslot_btn_clicked_from_success_page"
    const val TIMESLOT_BOTTOMSHEET_OPENED = "timeslot_bottomsheet_opened"

 //Events
 const val REGISER_BUTTON_CLICK_AT_HOME="register_button_click"
 const val ORDER_SUMMARY_SCREEN = "order_summary_screen"
 const val SINGLE_USER_ORDER_API_CALLED = "single_usr_order_api_called"
 const val MONTHLY_USER_ORDER_API_CALLED = "monthly_usr_order_api_called"
 const val OTP_SENT ="otp_sent"
 const val OTP_SUBMITTED_SUCCESSFULY ="otp_successfuly_submitted"
 const val LOGIN_PAGE ="login_page"
 const val LOGIN_PAGE_FROM_HOME ="login_page_from_home"
 const val LOGIN_PAGE_FROM_HOME_FOR_RAJNI ="login_page_from_home_from_rajni"
 const val REGISER_BUTTON_CLICK="register_button_click"
 const val REGISTERED_SUCCESSFULLY="registered_successfuly"
 const val SINGLE_MEAL_SELECTION_PAGE ="single_meal_selection_page"
 const val MONTHLY_FOOD_SELECTION_PAGE_FROM_HOME ="monthly_food_selection_page_from_home"
 const val MONTHLY_FOOD_SELECTION_PAGE ="monthly_food_selection_page"
 const val SINGLE_MEAL_SELECTION_PAGE_SCROLLED ="single_meal_selection_page_scrolled"
 const val SINGLE_MEAL_SCROLLED_AT_END ="single_meal_page_scrolled_at_end"
 const val SINGLE_MEAL_CONTINUE_BUTTON_CLICKED ="single_meal_continue_button_clicked"
}
